import type { CaseStudyInput } from "@/content/schema";

export const closeops: CaseStudyInput = {
  slug: "closeops",
  name: "CloseOps",
  title: "Provably duplicate-free multi-agent orchestration",
  outcome:
    "Five governed agents with a provable no-duplicate guarantee, applied to month-end close",
  whyFlagship:
    "Multi-agent orchestration with a hard, provable correctness guarantee. An orchestrator that cannot self-approve, and a forced retry storm that still yields zero duplicates. The guarantee is the transferable artefact; the close is where it was proven.",
  domain: "finance",
  order: 1,

  tldr:
    "CloseOps runs a synthetic month-end close with five governed agents. An orchestrator dispatches three specialists over the A2A protocol, humans approve at every risk boundary, and the orchestrator is structurally incapable of approving anything itself. A forced storm of thirty-six concurrent retries produced zero duplicate postings.",

  tags: ["multi-agent", "governance", "human-in-the-loop", "A2A protocol"],
  stack: ["Python", "LangGraph", "a2a-sdk 1.1.2", "FastAPI", "Postgres", "DuckDB", "React"],
  links: { repo: "https://github.com/Muhammad-Aneeq/closeops" },

  metrics: [
    {
      value: 0,
      label: "duplicate postings",
      note: "under a forced storm of 36 concurrent retries. Lower is better; the guarantee is that it cannot be anything else.",
    },
    { value: 169, label: "tests, green" },
    { value: 5, label: "human gates per close, none decidable by the orchestrator" },
    { value: 0, prefix: "£", label: "to run, no API key, no cloud" },
  ],

  problem: [
    "Month-end close is accounting's biggest bottleneck and the obvious thing to point agents at. It is also the worst possible place to let one act unsupervised. The failure mode is not a bad answer. It is a duplicate journal entry that somebody finds three weeks later, when the books have already been signed.",
    "So CloseOps is not a demo of agents doing a close. It is a demo of the machinery you need around them before you would let them: a checklist with a DAG and risk tiers, human gates at every risk boundary, idempotent dispatch, a variance narrative where every number is cross-checked against a query result, and an append-only close trace that reads as a handoff timeline.",
  ],

  transfers: [
    "The shape is idempotent multi-agent writes behind a separation-of-duties boundary, and the ledger is incidental. Claims adjudication has the same structure. An assessor agent that must not also authorise the payment, and a retry that must not pay twice.",
    "Procurement approval chains need the identical guarantee: a duplicate purchase order raised under a network timeout is the same defect as a duplicate journal entry, and the fix is the same deterministic key rather than a prompt asking the model to be careful.",
    "Anywhere an agent writes to a system of record more than once. Inventory adjustments, payroll runs, provisioning. The orchestrator-cannot-self-approve rule and the forced-retry test transfer unchanged.",
  ],

  constraints: [
    "Every ledger, counterparty and transaction is synthetic, generated by ledgerfab from a profile and an integer seed. Nothing is ever posted to a real system.",
    "A retry must be a no-op, not a second set of postings. Retries are most likely exactly where something has already succeeded.",
    "The orchestrator must not be able to approve its own work, and that must survive a refactor rather than resting on one assertion.",
    "Runs on a laptop with no API key, no Docker daemon and no cloud subscription.",
  ],

  architecture: {
    summary:
      "A LangGraph orchestrator holds no in-memory state. Postgres tables are the truth, and a close advances by invoking the graph repeatedly. It dispatches three specialists (reconciliation, accruals, variance) over the A2A protocol, each carrying an idempotency key. Gates open to a human and are decided through a signed callback that the Close Board and a Teams card both post to, identically.",
    trace: [
      {
        id: "plan",
        kind: "plan",
        label: "Checklist loaded",
        caption:
          "A DAG of seven tasks with risk tiers. The checklist declares requires_gate per task, and it is not believed.",
      },
      {
        id: "policy",
        kind: "policy",
        label: "Gate derived from policy",
        caption:
          "config/risk.yaml defines the tiers and the threshold. The loader refuses to start on a checklist that disagrees with it.",
      },
      {
        id: "dispatch",
        kind: "tool",
        label: "Dispatch over A2A",
        caption:
          "Each specialist is called with an idempotency key. The A2A layer covers in-flight work; the database carries the guarantee.",
      },
      {
        id: "halt",
        kind: "halt",
        label: "Planted anomaly halts",
        caption:
          "Account 1000: 17 of 17 transactions unmatched against a 55% tolerance. Not exceptions for review. The account's data is materially wrong. The task stops.",
      },
      {
        id: "gate",
        kind: "gate",
        label: "Escalated to a human",
        caption:
          "The gate opens. The orchestrator can open it and can never decide it, enforced at runtime and by a static import test.",
      },
      {
        id: "ground",
        kind: "route",
        label: "Narrative grounded",
        caption:
          "Every number in the variance draft is matched against a value a query actually returned. An unmatched figure raises, and nothing is emitted.",
      },
      {
        id: "commit",
        kind: "commit",
        label: "Posting written",
        caption:
          "UNIQUE(postings.idempotency_key) makes the write idempotent. Thirty-six concurrent retries produce one row.",
      },
      {
        id: "audit",
        kind: "audit",
        label: "Close trace appended",
        caption:
          "Append-only, exportable as JSON or CSV, and legible as a timeline of who handed what to whom.",
      },
    ],
  },

  adrs: [
    {
      decision: "Derive the gate requirement from a policy file, never from the checklist",
      alternatives:
        "Trust the checklist YAML's own requires_gate flag, which is what it is there for.",
      why: "The gate-correctness eval would then read requires_gate out of the checklist and assert that requires_gate is true. Grading the file that defines the answer. It would pass forever, including on the day somebody deletes a gate. Separating the policy from the checklist is what makes the eval capable of failing.",
    },
    {
      decision: "Make the orchestrator structurally incapable of approving, in three layers",
      alternatives: "A single runtime assertion, which is what the spec asks for.",
      why: "A hard rule enforced by one assert is one refactor away from being decoration. So: one module writes gates.decision; a runtime check refuses machine principals with normalisation; and a static test walks the orchestrator's imports and fails if that module is reachable at all. Its Dockerfile does not even copy the backend.",
    },
    {
      decision: "No LangGraph checkpointer, tables are the truth",
      alternatives:
        "The Postgres checkpointer the spec explicitly asks for. It was written, wired, and removed.",
      why: "CloseOps advances a close by invoking the graph repeatedly, and a checkpointer breaks that in four observed ways. The sharpest: re-invoking one thread_id resumes the finished graph, so the close silently stopped advancing and the retry drill fell from three postings to one with no error anywhere. The property the spec actually wants is proven harder instead. SIGKILL the orchestrator mid-dispatch and a fresh process finishes the close, which works precisely because there is no in-memory state to lose.",
    },
    {
      decision: "Carry idempotency on a database unique constraint, not the A2A task id",
      alternatives: "Derive the A2A task id from the idempotency key and let the protocol dedupe.",
      why: "The protocol corrected this twice. A task id cannot be derived from the key. Message.task_id means continue this task, so a first dispatch carrying a derived id gets TaskNotFoundError. And it cannot be reused after completion, because continuing a finished task is refused. So the A2A layer covers in-flight work only, and a design resting on it alone would have had a hole exactly where retries are most likely: after something already succeeded.",
    },
    {
      decision: "An ungrounded number fails the draft rather than annotating it",
      alternatives:
        "Emit the narrative with a caveat on unverified figures and let the reviewer judge.",
      why: "Numbers are extracted, normalised across thousands separators, currency, k/m suffixes, percentages and accounting parentheses, then matched against what the queries returned. Anything unmatched raises and nothing is emitted. The tolerance is deliberately absolute, not relative. 0.5% of a £53,000 opex line is £265, so a relative tolerance would wave through exactly the quietly-wrong figure the check exists to catch.",
    },
  ],

  evaluation: {
    summary:
      "Three evals plus two adversarial drills. The gate-correctness eval ships with a negative control that must fail, because an eval that cannot fail is decoration. The drills print which database they ran against and refuse to describe a SQLite pass as proof.",
    rows: [
      { metric: "Gate-correctness eval", result: "green", note: "and its negative control fails, as it must" },
      { metric: "Idempotency drill", result: "0 duplicates", note: "36 concurrent forced retries, on SQLite" },
      { metric: "Restart drill", result: "close completes", note: "real SIGKILL mid-dispatch, fresh process finishes" },
      { metric: "Grounding", result: "0 unqueried numbers", note: "structural, tested in both directions" },
      { metric: "Test suite", result: "169 passing" },
      { metric: "A2A contract suite", result: "green", note: "real protocol, real ASGI apps, no mocked transport" },
    ],
  },

  shots: [
    {
      src: "/media/closeops/board.png",
      width: 1440,
      height: 980,
      alt: "The CloseOps board: seven tasks in four columns by dependency depth, each with risk tier and gate chips. One reconciliation task is red.",
      caption:
        "A completed close. Seven tasks, three specialists, five gates, and the planted anomaly in red: account 1000, 17 of 17 transactions unmatched against a 55% tolerance, escalated and resolved by a human.",
    },
    {
      src: "/media/closeops/gates.png",
      width: 1440,
      height: 980,
      alt: "The gate queue, listing tasks awaiting a human decision with their risk tier and the reason each was gated.",
      caption:
        "The gate queue. It mirrors the Teams card and posts the same signed callback, so the console has no privileged path of its own.",
    },
    {
      src: "/media/closeops/summary.png",
      width: 1440,
      height: 980,
      alt: "The close summary: time to close, tasks auto-completed versus gated, anomalies caught, and duplicate postings.",
      caption:
        "The summary the whole project exists to produce: auto versus gated, anomalies caught, escalations, and duplicate postings at zero.",
    },
  ],

  limits: [
    "The idempotency and restart drills were verified on SQLite, not Postgres. No Docker daemon was available in the build environment. The guarantees are transactional, so a SQLite pass is suggestive, not proof. The drills print which database they ran against and refuse to claim otherwise.",
    "It has never been deployed to Azure. Every Bicep template compiles and the deploy runbook has every human step, including the two that cannot be templated, but nothing in the repository claims to be deployed.",
    "MODEL_MODE=mock is the default and the tested path, because no API key was available. Nothing here is evidence about how a real model behaves. The governance claims hold because they never ask a model how sure it is.",
    "The reconciliation specialist is a labelled stub, not LedgerGuard. It does real matching on real ledgerfab data and escalates what it cannot resolve, but it lacks LedgerGuard's confidence scorer and evals gate, and it says so on its own agent card.",
    "The variance drafter is grounded in a local DuckDB star schema rather than FinSight, which is spec-only. CloseOps owns the AskAdapter interface that was supposed to already exist.",
  ],
};
